src/main/java/com/humanbooster/trainings/myjeeapp/entity/Account.java
package com.humanbooster.trainings.myjeeapp.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.validation.constraints.NotNull;


/**
 * The persistent class for the account database table.
 * 
 */
@Entity
@NamedQuery(name="Account.findAll", query="SELECT a FROM Account a")
public class Account implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;

	@NotNull
	private String email;

	private String password;

	private String username;

	public Account() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + id;
		result = prime * result
				+ ((password == null) ? 0 : password.hashCode());
		result = prime * result
				+ ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Account other = (Account) obj;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (id != other.id)
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Account [id=" + id + ", email=" + email + ", password="
				+ password + ", username=" + username + "]";
	}
	
	

}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/AccountBean.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.humanbooster.trainings.myjeeapp.ejb.AccountService;
import com.humanbooster.trainings.myjeeapp.entity.Account;

@Named
@RequestScoped
public class AccountBean {

	private int id;
	
	private Account account;

	@Inject
	AccountService accountService;
	
	public void init() {
		account = accountService.findAccountById(id);
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public Account getAccount() {
		return account;
	}
	
	

}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/AccountRegistration.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.humanbooster.trainings.myjeeapp.constraints.Email;
import com.humanbooster.trainings.myjeeapp.ejb.AccountService;
import com.humanbooster.trainings.myjeeapp.entity.Account;

@Named
@ViewScoped
public class AccountRegistration implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@NotNull(message="Please enter a username")
	private String username;
	@NotNull(message="Please enter an email") 
	@Email(message="Please enter a valid email")
	private String email;
	@NotNull(message="Please enter a password")
	private String password;
	
	@Inject
	AccountService accountService;
	
	@PostConstruct // do some stuff after object construction and dependency injection resolved
	public void init() {
	}
	
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}
	
	public String create() {
		Account account = accountService.createAccount(username, email, password);
		//TODO catch exception => postback or post to error message
		//TODO pas d'exception redirect to homepage
		return "index.xhtml?faces-redirect=true";
		//return "index.xhtml";
	}

}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/AccountsBean.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.humanbooster.trainings.myjeeapp.ejb.AccountService;
import com.humanbooster.trainings.myjeeapp.entity.Account;

@RequestScoped
@Named
public class AccountsBean {

	@Inject
	private AccountService accountService;
	
	private int page;
	private boolean hasPrevious;
	private boolean hasNext;
	private int offset;
	private final int maxResultsPerPage = 5;

	public void setPage(int page) {
		this.page = page;
	}
	
	public int getPage() {
		return page;
	}
	
	public void init() {
		//init pagination
		// getAccount count
		long totalAccounts = accountService.countAccounts();
		// check if current page fits
		
		// paginate
		offset = page * maxResultsPerPage;
		hasPrevious = (page > 0);
		hasNext = (offset + maxResultsPerPage < totalAccounts);
	}
	
	public boolean isHasPrevious() {
		return hasPrevious;
	}
	
	public boolean isHasNext() {
		return hasNext;
	}
	
	public List<Account> getAccounts() {
		return accountService.findAllAccounts(offset, maxResultsPerPage);
	}
}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/App.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class App {

	public String getName() {
		return "My Jee App";
	}
}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/BackingBeanDemo.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.humanbooster.trainings.myjeeapp.ejb.AccountService;
import com.humanbooster.trainings.myjeeapp.entity.Account;

@Named
@RequestScoped
public class BackingBeanDemo {

	@Inject
	AccountService accountService;
	
	Account account;
	
	private String hello = "Hello World";
	
	public String getHello() {
		return hello;
	}
	
	public Account getAccount() {
		if(account == null) {
			account = accountService.findAccountById(20);
		}
		return account;
	}
	
	public List<Account> getAccounts() {
		return accountService.findAllAccounts();
	}
}

src/main/java/com/humanbooster/trainings/myjeeapp/jsf/beans/Time.java
package com.humanbooster.trainings.myjeeapp.jsf.beans;

import java.util.Date;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class Time {
	public Date getDate() {
		return new Date();
	}
}

src/main/webapp/account-creation.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="template.xhtml">
		<ui:define name="title">
		Create a new account
		</ui:define>
		<ui:define name="header">
			<h1>Create a new account</h1>
		</ui:define>
		<ui:define name="content">
			<h:form>
				<table>
					<tr>
						<td><h:outputLabel for="username">Username</h:outputLabel></td>
						<td><h:inputText id="username"
								value="#{accountRegistration.username}"
								p:placeholder="Enter the username" />
								</td>
						<td><h:message id="usernameMessage" for="username" /></td>
					</tr>
					<tr>
						<td><h:outputLabel for="email">Email</h:outputLabel></td>
						<td><h:inputText id="email"
								value="#{accountRegistration.email}"
								p:placeholder="Enter the email" /></td>
						<td><h:message id="emailMessage" for="email" /></td>
					</tr>
					<tr>
						<td><h:outputLabel for="password">Password</h:outputLabel></td>
						<td><h:inputSecret id="password"
								value="#{accountRegistration.password}"
								p:placeholder="Enter the password" /></td>
						<td><h:message id="passwordMessage" for="password" /></td>
					</tr>
					<tr>
						<td colspan="3"><h:commandButton value="Create account"
								action="#{accountRegistration.create}" /></td>
					</tr>
				</table>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/account-list.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
	<ui:composition template="template.xhtml">
		<ui:insert name="metadata">
			<f:metadata>
				<f:viewParam id="id" name="page" value="#{accountsBean.page}" />
				<f:viewAction action="#{accountsBean.init}" />
			</f:metadata>
		</ui:insert>
		<ui:define name="title">Accounts</ui:define>
		<ui:define name="header">
			<h1>Accounts</h1>
		</ui:define>
		<ui:define name="content">
			<h:dataTable id="accounts" value="#{accountsBean.accounts}" var="account">
				<h:column>
					<f:facet name="header">username</f:facet>
					<h:link outcome="account-show" value="#{account.username}">
						<f:param name="id" value="#{account.id}" />
					</h:link>
				</h:column>
			</h:dataTable>
			<h:link outcome="account-list" value="previous" rendered="#{accountsBean.hasPrevious}">
				<f:param name="page" value="#{accountsBean.page - 1}" />
			</h:link>
			<h:link outcome="account-list" value="next" rendered="#{accountsBean.hasNext}">
				<f:param name="page" value="#{accountsBean.page + 1}" />
			</h:link>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/account-show.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
	<ui:composition template="template.xhtml">
		<ui:insert name="metadata">
			<f:metadata>
				<f:viewParam id="id" name="id" value="#{accountBean.id}" />
				<f:viewAction action="#{accountBean.init}" />
			</f:metadata>
		</ui:insert>
		<ui:define name="title">Account #{accountBean.account.id}</ui:define>
		<ui:define name="header">
			<h1>Account #{accountBean.account.id}</h1>
		</ui:define>
		<ui:define name="content">
		#{accountBean.account.username}
		<h:link outcome="account-list" value="accounts" />
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:body>
	<ui:composition template="template.xhtml">
		<ui:define name="title">My JEE App</ui:define>
		<ui:define name="header">
			<h1>My JEE App</h1>
			<h:graphicImage library="mytheme" name="images/java_duke.jpg" />
		</ui:define>
		<ui:define name="content">
			<h2>Welcome to #{app.name}</h2>
			<p:colorPicker value="#{colorView.colorInline}" mode="inline" />
			<h:outputText value="It is #{time.date}">
				<f:convertDateTime dateStyle="long" type="date" />
			</h:outputText>
			<br />
			<h:outputText value="#{time.date}" converter="myDateTimeConverter" />
			<br />
			<h:link value="Create an account" outcome="account-creation" />
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/jsfdemo.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet"
		href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
	<!-- Latest compiled and minified JavaScript -->
	<script
		src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</h:head>
<h:body>
	<div id="container">
		<div class="row">
			<div class="col-md-8">
				<h:outputText value="Hello World" />
				<h:outputText value="#{backingBeanDemo.hello}" />
			</div>
			<div class="col-md-4">
				<h1>#{backingBeanDemo.hello}</h1>
				<ul>
					<li>#{backingBeanDemo.account.username}</li>
					<li>#{backingBeanDemo.account.email}</li>
				</ul>
			</div>
		</div>
	</div>
	<h:dataTable value="#{backingBeanDemo.accounts}" var="account">
		<h:column>
			<f:facet name="header">
				<h:outputText value="Username" />
			</f:facet>
		#{account.username}
    </h:column>
		<h:column>
			<f:facet name="header">
				<h:outputText value="Email" />
			</f:facet>
        #{account.email}
    </h:column>
	</h:dataTable>
</h:body>
</html>

src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html">
<ui:insert name="metadata"></ui:insert>
<h:head>
	<!-- <h:outputStylesheet id="default" name="default.css"
		<h:outputStylesheet name="cssLayout.css" /> -->
		<title><ui:insert name="title"></ui:insert></title>
</h:head>
<h:body>
	<header>
		<ui:insert name="header">Title content</ui:insert>
	</header>
	<div>
		<ui:insert name="content">Content</ui:insert>
	</div>
</h:body>
</html>